Starting GRASS GIS...
Creating new GRASS GIS location <tmploc>...
Cleaning up temporary files...
Executing <python3 get_scenes_list.py> ...
T31
B
Traceback (most recent call last):
  File "get_scenes_list.py", line 18, in <module>
    print(f"{year}")
NameError: name 'year' is not defined
Execution of <python3 get_scenes_list.py> finished.
Cleaning up temporary files...
